### ISSUE TITLE
array looping issue when used with Prototype or Mootools framework

### ISSUE THREAD

**Issue by pandavault** [azicchetti/jquerymobile-router#14]
when using with Prototype or a similar framework that extends Array functionality (http://www.prototypejs.org/api/array), the for... in method of looping (line 147 jquery.mobile.router.js) will treat all extended array methods as properties to loop through, and will cause a lot of errors!

**Comment by azicchetti** [comment]
I've never thought of using jQuery Mobile with other javascript frameworks, such as Prototype or Mootools.

Is there a particular reason you can't replace Mootools with jQuery?

It's important for mobile applications/websites to minimize the javascript memory footprint and loading another "useless" framework doesn't sound like a good idea to me.

**Comment by pandavault** [comment]
I like the Object-Oriented inheritence framework that Prototype provides, which is very helpful to have for structuring bigger projects. This is not exclusively a Prototype/Mootools related issue though, any frameworks or plugins that extends Array functionalities are likely to run into this issue.

**Comment by azicchetti** [comment]
Fixed! Thank you.

I may suggest a very nice and small plugin to have OO support in jQuery, even if I don't find it particularly useful when used in a Backbone project:

http://code.google.com/p/jquery-klass/

**Comment by pandavault** [comment]
ah thanks for that! Good to know.
