### ISSUE TITLE
Unable to modify changePage options

### ISSUE THREAD

**Issue by raldred** [azicchetti/jquerymobile-router#15]
The router is listening to pagebeforechange and taking over control of calling changePage
However I can't find anyway I can specify different changePage options depending on the route being called.
There is no `data-change-hash="false"` attribute in jqm

I want to show my own a help dialog (which is just another embedded page) but without using jqm's actual dialogs eg. data-rel="dialog"
I want to load the page but prevent it from being added to the history just like jqm dialogs.

something like:

```
new $.mobile.Router({\
  ...
  "#help": { handler: "showHelp", events: "bs", changeHash: false }
  ...
});
```

Alternatively it'd be nice to have a way in my handler to tell the router that i'll handle the call to changePage for a particular route.

**Comment by azicchetti** [comment]
Hi,
the router binds to pagebeforechange just to provide support for hash parameters and thus this event is not meant to be exposed to the user.

I get what you're trying to do and I think the best way to achieve your desired behavior is using the data-rel="dialog" attribute on the anchor that points to "#help". Please note that using this anchor doesn't prevent you from showing the help as a standard jquery mobile page using other links without the data-rel attribute.

Another option would be using data-role="dialog" on the #help page.

Hope this helps.

**Comment by raldred** [comment]
Ok I will use the dialog for now, I wanted to avoid them because they are not in-keeping with the flow of my app, however not tracking in history is more important at this stage.

Thanks for clarification on this.
