### ISSUE TITLE
Make a minified jquery.mobile.router.min.js dist available

### ISSUE THREAD

**Issue by marceloverdijk** [azicchetti/jquerymobile-router#17]
Not a showstopper, but it would be nice to offer a minified jquery.mobile.router.min.js distribution.

**Comment by azicchetti** [comment]
Yeah, it's a good idea, I've just pushed a minified version to the git.

Thank you!

**Comment by marceloverdijk** [comment]
That's quick.

Maybe it's good to preserve the version on the first line of the minified file.
Just to know which version is in use.

E.g. just like Backbone is doing: http://backbonejs.org/backbone-min.js
They also provide a VERSION field.

**Comment by azicchetti** [comment]
Fixed!

**Comment by marceloverdijk** [comment]
Great!
