### ISSUE TITLE
Documentation error in getParams

### ISSUE THREAD

**Issue by marceloverdijk** [azicchetti/jquerymobile-router#18]
The getParams documentation contains:

getParams(hashPartOfTheUrl): Returns an object with the parameters encoded in the url or null if nothing's found. For instance, if you have something like: #detail?id=3&foo=bar and call routerInstance.getParams("?id=3&foo=bar") you'll get: javascript { id: "3", foo: "bar" }

I think 

routerInstance.getParams("?id=3&foo=bar")

should be something like:

routerInstance.getParams(match[1])

**Comment by azicchetti** [comment]
Hi,
the match[1] argument works only if one uses the regexp provided in the example, but I'll update the doc to make that part more clear. Thank you!
