### ISSUE TITLE
PushState Question

### ISSUE THREAD

**Issue by andyl** [azicchetti/jquerymobile-router#2]
I was curious if jquerymobile-router supports PushState, to eliminate the need for hashes on modern browsers.

Tx, Andy

**Comment by azicchetti** [comment]
Yes!
Luckily the pushState feature of jquery mobile doesn't change the way routes are dispatched (this is an important benefit of the pagechange hack proposed in the official documentation).

Sorry for the late answer but I missed the notification when this issue was opened.
