### ISSUE TITLE
multiple routes matched

### ISSUE THREAD

**Issue by stephenhandley** [azicchetti/jquerymobile-router#26]
I'm seeing multiple routes matched when they share a common prefix. Seems the first defined route should take precedence:

``` javascript
var router=new $.mobile.Router([
  {"#blahs_year\\?year=(\\d{4})": {handler: Controller.blahs_year, events: "bs,h"}},
  {"#blahs(?:\\?tab=(.*))?": {handler: Controller.blahs, events: "bs,h" }}
], {}, {
  defaultHandler: function(type, ui, page) {
    console.log("Unmatched route (" + type + ", " + ui + ", " + page + ")");
  },
  defaultHandlerEvents: 'bs,h'
});
```

I'm getting around it by changing the route hash, but I think it would be better if only a single route was matched.

**Comment by azicchetti** [comment]
Hi,
I'm afraid this is actually a "feature". It may sound strange, but I know a few people (including myself) that use multiple matches to render different parts of the page in certain applications.

For example, content is rendered by a "list.html(?:....ecc)" regexp, while header and footer are generated through a "." regexp that matches every page.

Mobile websites may also use this technique to track page views through analytics (using a general handler for pageshow that calls _trackPageview).

However, I'm planning to add a status variable in the router, that counts how many handlers are called for the current event.
In your example, the status variable would hold 0 when Controller.blahs_year is executed during beforeshow, and 1 when Controller.blahs is called.
Same thing for the hide event (it's resetted to 0 when the event changes).
Hope it sounds a viable solution to cover scenarios like the one you presented.

Cheers,
        Andrea

**Comment by stephenhandley** [comment]
Hi Andrea,

Thanks for the response.. I was thinking that the behavior was probably on purpose right after filing the issue. I can see how that flexibility makes sense in those cases. 

As far as the router status variable goes, if its possible, I think a mobileinit configuration option would probably be cleaner for usage than a status counter (or at least in addition to). To specify only a single match being allowed, users could do something like:

``` javascript
 $(document).bind("mobileinit",function(){
        $.mobile.jqmRouter={
          firstMatchOnly: true
        };
    });
```

which would result in only the first match being dispatched to. firstMatchOnly would default to false, which would result in the current behavior.

Thanks!
Stephen

**Comment by azicchetti** [comment]
Hi,
a configuration option makes much more sense than a status variable, thank you for the idea.

I'll try to push the fix in the next few hours.

Cheers,
        Andrea

**Comment by stephenhandley** [comment]
Awesome, thanks!
