### ISSUE TITLE
Routing on form submission (GET method) does not seem to work

### ISSUE THREAD

**Issue by chrisben** [azicchetti/jquerymobile-router#30]
I want to be able to submit a simple form with only a query parameter (think google home page) that would open a separate page (#page-search) with the search results. I am working on a single file multipage app.
Here's the html code:

``` html
<div data-role="page" id="page-home">
 [...]
<form action="#page-search" method="get">
<input name="q" type="text" required="required" value="" />
<input type="submit" />
</form>
 [...]
</div>
<div data-role="page" id="page-search">
 [...]
```

The router code:

``` javascript
'#page-search[?]q=(.*)': { handler: 'pageSearch', events: 'bs' }
```

That handler would then retrieve the query parameter (matchObj[1]) and then fetch a list of results from the server to populate that new page.

Now when I click on submit the router handler pageSearch is never called, instead I can see the url being changed to "?q=mysearchterm".

Could you please tell me if I've done something wrong there?

Cheers and thanks for your work on this project!

**Comment by azicchetti** [comment]
Hi,
unfortunately jquery mobile doesn't support form submission to local pages in a multipage application.

However, we can get your desired behavior with a little javascript (I don't know whether you are using backbone or not, so I'll go for plain jquery):

``` javascript
        var C={
                pageSearch: function(t,m){
                        alert(m[1]);
                },
                pageHome: function(t,m,ui,p,e){
                        $(p).find("form").submit(function(e){
                                e.preventDefault();
                                e.stopPropagation();
                                $.mobile.changePage("#page-search?"+$(this).serialize());
                        });
                }
        };
        var router=new $.mobile.Router([
                { "#page-search[?]q=(.*)": "pageSearch" },
                { "#page-home": { events: "i", handler: "pageHome" } }
        ], C);
```

The pageinit event is used to install a submit handler on the form. In this handler, we build the query string and perform a "manual" page change to the destination page with the proper query parameter.

Hope this can solve your problem!

Cheers,
        Andrea

**Comment by chrisben** [comment]
ok, I see what you mean.. Sure I'll do it this way then!

cheers!
