### ISSUE TITLE
Is JQM Router ready for JQM 1.1 Final?

### ISSUE THREAD

**Issue by ghost** [azicchetti/jquerymobile-router#40]
Is the JQM router project compatible with/ready for JQM 1.1 Final?

Thanks,

TR

**Comment by azicchetti** [comment]
Hi,
everything seems to work as expected with the 1.1.0 final, hopefully there won't be issues with this release.

I'm waiting for feedback about potential problems with manual changePage() calls, but I can't reproduce the problem that was reported in #39, so it might be something related to that particular application.

Cheers,
        Andrea

**Comment by ghost** [comment]
Thanks Andrea.

TR
