### ISSUE TITLE
Missing router.navigate() method

### ISSUE THREAD

**Issue by fbuchinger** [azicchetti/jquerymobile-router#43]
Thanks for developing jquerymobile-router, it really helps me to integrate my backbone app with jquery mobile.

One thing I'm missing though is the [navigate method of Backbone Router](http://documentcloud.github.com/backbone/#Router-navigate). It allows me to manually trigger routes without forcing the user to click on buttons etc.

**Comment by azicchetti** [comment]
Hi,
the router.navigate() method can be replaced (it's not a 1:1 replacement but it should cover about 90% of the cases) by jquery mobile $.mobile.changePage() method.

Here you can find the documentation: http://jquerymobile.com/demos/1.1.0/docs/api/methods.html

Hope this helps you!

Cheers,
        Andrea
