### ISSUE TITLE
DefaultHandler does not work

### ISSUE THREAD

**Issue by mrbhandari** [azicchetti/jquerymobile-router#60]
Hi - 
First of all thank you for putting this code out there - its been very helpful. 

I'm trying to implement DefaultHandler and noticed that testAjax.html included in the example files does not actually call DefaultRouter. What is the correct syntax?

Thanks

**Comment by mrbhandari** [comment]
Sorry meant to add if you go to textAjax.html and then testAjax1.html ... the DefaultRouter is not called and the page is not found

**Comment by azicchetti** [comment]
Hi @mrbhandari,
the default handler doesn't get called when you reference a non-existing page.
In that case jQM will handle the error displaying the classic "error loading page" overlay.

However, default handlers are called when you go to an existing page that isn't matched by any route.

If you want to see an example of this behavior:

```
    * create a __subTestAjax2.html page
    * add a link to the the newly created page in testAjax.html
    * click on the link
```

The default handler will get called 'cause __subTestAjax2.html is not matched by anything.
