### ISSUE TITLE
production ready?

### ISSUE THREAD

**Issue by siddo420** [azicchetti/jquerymobile-router#82]
thanks for the good work

just wanted to know if this plugin is ready for use in production? is anyone using t in production?

i haven't seen this plugin mentioned in books i've read so far

**Comment by azicchetti** [comment]
Hi,
I've used it for a lot of production projects, but they where all based on jQM <= 1.3.x, it should work with 1.4 though. When 1.5 is out, I'll definitely try to support it.

On a side note, in the company where I work we've switched to another framework 'cause it seems that jQM is not on par with other paid solutions in the hybrid app development department, so I suggest you have a good look around before sticking with jQM.

Cheers,
    Andrea
